	base_hps u0 (
		.clk_clk                            (<connected-to-clk_clk>),                            //                         clk.clk
		.hps_0_ddr_mem_a                    (<connected-to-hps_0_ddr_mem_a>),                    //                   hps_0_ddr.mem_a
		.hps_0_ddr_mem_ba                   (<connected-to-hps_0_ddr_mem_ba>),                   //                            .mem_ba
		.hps_0_ddr_mem_ck                   (<connected-to-hps_0_ddr_mem_ck>),                   //                            .mem_ck
		.hps_0_ddr_mem_ck_n                 (<connected-to-hps_0_ddr_mem_ck_n>),                 //                            .mem_ck_n
		.hps_0_ddr_mem_cke                  (<connected-to-hps_0_ddr_mem_cke>),                  //                            .mem_cke
		.hps_0_ddr_mem_cs_n                 (<connected-to-hps_0_ddr_mem_cs_n>),                 //                            .mem_cs_n
		.hps_0_ddr_mem_ras_n                (<connected-to-hps_0_ddr_mem_ras_n>),                //                            .mem_ras_n
		.hps_0_ddr_mem_cas_n                (<connected-to-hps_0_ddr_mem_cas_n>),                //                            .mem_cas_n
		.hps_0_ddr_mem_we_n                 (<connected-to-hps_0_ddr_mem_we_n>),                 //                            .mem_we_n
		.hps_0_ddr_mem_reset_n              (<connected-to-hps_0_ddr_mem_reset_n>),              //                            .mem_reset_n
		.hps_0_ddr_mem_dq                   (<connected-to-hps_0_ddr_mem_dq>),                   //                            .mem_dq
		.hps_0_ddr_mem_dqs                  (<connected-to-hps_0_ddr_mem_dqs>),                  //                            .mem_dqs
		.hps_0_ddr_mem_dqs_n                (<connected-to-hps_0_ddr_mem_dqs_n>),                //                            .mem_dqs_n
		.hps_0_ddr_mem_odt                  (<connected-to-hps_0_ddr_mem_odt>),                  //                            .mem_odt
		.hps_0_ddr_mem_dm                   (<connected-to-hps_0_ddr_mem_dm>),                   //                            .mem_dm
		.hps_0_ddr_oct_rzqin                (<connected-to-hps_0_ddr_oct_rzqin>),                //                            .oct_rzqin
		.hps_0_io_hps_io_emac1_inst_TX_CLK  (<connected-to-hps_0_io_hps_io_emac1_inst_TX_CLK>),  //                    hps_0_io.hps_io_emac1_inst_TX_CLK
		.hps_0_io_hps_io_emac1_inst_TXD0    (<connected-to-hps_0_io_hps_io_emac1_inst_TXD0>),    //                            .hps_io_emac1_inst_TXD0
		.hps_0_io_hps_io_emac1_inst_TXD1    (<connected-to-hps_0_io_hps_io_emac1_inst_TXD1>),    //                            .hps_io_emac1_inst_TXD1
		.hps_0_io_hps_io_emac1_inst_TXD2    (<connected-to-hps_0_io_hps_io_emac1_inst_TXD2>),    //                            .hps_io_emac1_inst_TXD2
		.hps_0_io_hps_io_emac1_inst_TXD3    (<connected-to-hps_0_io_hps_io_emac1_inst_TXD3>),    //                            .hps_io_emac1_inst_TXD3
		.hps_0_io_hps_io_emac1_inst_RXD0    (<connected-to-hps_0_io_hps_io_emac1_inst_RXD0>),    //                            .hps_io_emac1_inst_RXD0
		.hps_0_io_hps_io_emac1_inst_MDIO    (<connected-to-hps_0_io_hps_io_emac1_inst_MDIO>),    //                            .hps_io_emac1_inst_MDIO
		.hps_0_io_hps_io_emac1_inst_MDC     (<connected-to-hps_0_io_hps_io_emac1_inst_MDC>),     //                            .hps_io_emac1_inst_MDC
		.hps_0_io_hps_io_emac1_inst_RX_CTL  (<connected-to-hps_0_io_hps_io_emac1_inst_RX_CTL>),  //                            .hps_io_emac1_inst_RX_CTL
		.hps_0_io_hps_io_emac1_inst_TX_CTL  (<connected-to-hps_0_io_hps_io_emac1_inst_TX_CTL>),  //                            .hps_io_emac1_inst_TX_CTL
		.hps_0_io_hps_io_emac1_inst_RX_CLK  (<connected-to-hps_0_io_hps_io_emac1_inst_RX_CLK>),  //                            .hps_io_emac1_inst_RX_CLK
		.hps_0_io_hps_io_emac1_inst_RXD1    (<connected-to-hps_0_io_hps_io_emac1_inst_RXD1>),    //                            .hps_io_emac1_inst_RXD1
		.hps_0_io_hps_io_emac1_inst_RXD2    (<connected-to-hps_0_io_hps_io_emac1_inst_RXD2>),    //                            .hps_io_emac1_inst_RXD2
		.hps_0_io_hps_io_emac1_inst_RXD3    (<connected-to-hps_0_io_hps_io_emac1_inst_RXD3>),    //                            .hps_io_emac1_inst_RXD3
		.hps_0_io_hps_io_sdio_inst_CMD      (<connected-to-hps_0_io_hps_io_sdio_inst_CMD>),      //                            .hps_io_sdio_inst_CMD
		.hps_0_io_hps_io_sdio_inst_D0       (<connected-to-hps_0_io_hps_io_sdio_inst_D0>),       //                            .hps_io_sdio_inst_D0
		.hps_0_io_hps_io_sdio_inst_D1       (<connected-to-hps_0_io_hps_io_sdio_inst_D1>),       //                            .hps_io_sdio_inst_D1
		.hps_0_io_hps_io_sdio_inst_CLK      (<connected-to-hps_0_io_hps_io_sdio_inst_CLK>),      //                            .hps_io_sdio_inst_CLK
		.hps_0_io_hps_io_sdio_inst_D2       (<connected-to-hps_0_io_hps_io_sdio_inst_D2>),       //                            .hps_io_sdio_inst_D2
		.hps_0_io_hps_io_sdio_inst_D3       (<connected-to-hps_0_io_hps_io_sdio_inst_D3>),       //                            .hps_io_sdio_inst_D3
		.hps_0_io_hps_io_usb1_inst_D0       (<connected-to-hps_0_io_hps_io_usb1_inst_D0>),       //                            .hps_io_usb1_inst_D0
		.hps_0_io_hps_io_usb1_inst_D1       (<connected-to-hps_0_io_hps_io_usb1_inst_D1>),       //                            .hps_io_usb1_inst_D1
		.hps_0_io_hps_io_usb1_inst_D2       (<connected-to-hps_0_io_hps_io_usb1_inst_D2>),       //                            .hps_io_usb1_inst_D2
		.hps_0_io_hps_io_usb1_inst_D3       (<connected-to-hps_0_io_hps_io_usb1_inst_D3>),       //                            .hps_io_usb1_inst_D3
		.hps_0_io_hps_io_usb1_inst_D4       (<connected-to-hps_0_io_hps_io_usb1_inst_D4>),       //                            .hps_io_usb1_inst_D4
		.hps_0_io_hps_io_usb1_inst_D5       (<connected-to-hps_0_io_hps_io_usb1_inst_D5>),       //                            .hps_io_usb1_inst_D5
		.hps_0_io_hps_io_usb1_inst_D6       (<connected-to-hps_0_io_hps_io_usb1_inst_D6>),       //                            .hps_io_usb1_inst_D6
		.hps_0_io_hps_io_usb1_inst_D7       (<connected-to-hps_0_io_hps_io_usb1_inst_D7>),       //                            .hps_io_usb1_inst_D7
		.hps_0_io_hps_io_usb1_inst_CLK      (<connected-to-hps_0_io_hps_io_usb1_inst_CLK>),      //                            .hps_io_usb1_inst_CLK
		.hps_0_io_hps_io_usb1_inst_STP      (<connected-to-hps_0_io_hps_io_usb1_inst_STP>),      //                            .hps_io_usb1_inst_STP
		.hps_0_io_hps_io_usb1_inst_DIR      (<connected-to-hps_0_io_hps_io_usb1_inst_DIR>),      //                            .hps_io_usb1_inst_DIR
		.hps_0_io_hps_io_usb1_inst_NXT      (<connected-to-hps_0_io_hps_io_usb1_inst_NXT>),      //                            .hps_io_usb1_inst_NXT
		.hps_0_io_hps_io_uart0_inst_RX      (<connected-to-hps_0_io_hps_io_uart0_inst_RX>),      //                            .hps_io_uart0_inst_RX
		.hps_0_io_hps_io_uart0_inst_TX      (<connected-to-hps_0_io_hps_io_uart0_inst_TX>),      //                            .hps_io_uart0_inst_TX
		.hps_0_io_hps_io_i2c0_inst_SDA      (<connected-to-hps_0_io_hps_io_i2c0_inst_SDA>),      //                            .hps_io_i2c0_inst_SDA
		.hps_0_io_hps_io_i2c0_inst_SCL      (<connected-to-hps_0_io_hps_io_i2c0_inst_SCL>),      //                            .hps_io_i2c0_inst_SCL
		.hps_0_io_hps_io_gpio_inst_GPIO53   (<connected-to-hps_0_io_hps_io_gpio_inst_GPIO53>),   //                            .hps_io_gpio_inst_GPIO53
		.hps_0_io_hps_io_gpio_inst_GPIO54   (<connected-to-hps_0_io_hps_io_gpio_inst_GPIO54>),   //                            .hps_io_gpio_inst_GPIO54
		.hps_0_spim0_txd                    (<connected-to-hps_0_spim0_txd>),                    //                 hps_0_spim0.txd
		.hps_0_spim0_rxd                    (<connected-to-hps_0_spim0_rxd>),                    //                            .rxd
		.hps_0_spim0_ss_in_n                (<connected-to-hps_0_spim0_ss_in_n>),                //                            .ss_in_n
		.hps_0_spim0_ssi_oe_n               (<connected-to-hps_0_spim0_ssi_oe_n>),               //                            .ssi_oe_n
		.hps_0_spim0_ss_0_n                 (<connected-to-hps_0_spim0_ss_0_n>),                 //                            .ss_0_n
		.hps_0_spim0_ss_1_n                 (<connected-to-hps_0_spim0_ss_1_n>),                 //                            .ss_1_n
		.hps_0_spim0_ss_2_n                 (<connected-to-hps_0_spim0_ss_2_n>),                 //                            .ss_2_n
		.hps_0_spim0_ss_3_n                 (<connected-to-hps_0_spim0_ss_3_n>),                 //                            .ss_3_n
		.hps_0_spim0_sclk_out_clk           (<connected-to-hps_0_spim0_sclk_out_clk>),           //        hps_0_spim0_sclk_out.clk
		.hps_0_spim1_txd                    (<connected-to-hps_0_spim1_txd>),                    //                 hps_0_spim1.txd
		.hps_0_spim1_rxd                    (<connected-to-hps_0_spim1_rxd>),                    //                            .rxd
		.hps_0_spim1_ss_in_n                (<connected-to-hps_0_spim1_ss_in_n>),                //                            .ss_in_n
		.hps_0_spim1_ssi_oe_n               (<connected-to-hps_0_spim1_ssi_oe_n>),               //                            .ssi_oe_n
		.hps_0_spim1_ss_0_n                 (<connected-to-hps_0_spim1_ss_0_n>),                 //                            .ss_0_n
		.hps_0_spim1_ss_1_n                 (<connected-to-hps_0_spim1_ss_1_n>),                 //                            .ss_1_n
		.hps_0_spim1_ss_2_n                 (<connected-to-hps_0_spim1_ss_2_n>),                 //                            .ss_2_n
		.hps_0_spim1_ss_3_n                 (<connected-to-hps_0_spim1_ss_3_n>),                 //                            .ss_3_n
		.hps_0_spim1_sclk_out_clk           (<connected-to-hps_0_spim1_sclk_out_clk>),           //        hps_0_spim1_sclk_out.clk
		.hps_0_i2c1_scl_in_clk              (<connected-to-hps_0_i2c1_scl_in_clk>),              //           hps_0_i2c1_scl_in.clk
		.hps_0_uart1_cts                    (<connected-to-hps_0_uart1_cts>),                    //                 hps_0_uart1.cts
		.hps_0_uart1_dsr                    (<connected-to-hps_0_uart1_dsr>),                    //                            .dsr
		.hps_0_uart1_dcd                    (<connected-to-hps_0_uart1_dcd>),                    //                            .dcd
		.hps_0_uart1_ri                     (<connected-to-hps_0_uart1_ri>),                     //                            .ri
		.hps_0_uart1_dtr                    (<connected-to-hps_0_uart1_dtr>),                    //                            .dtr
		.hps_0_uart1_rts                    (<connected-to-hps_0_uart1_rts>),                    //                            .rts
		.hps_0_uart1_out1_n                 (<connected-to-hps_0_uart1_out1_n>),                 //                            .out1_n
		.hps_0_uart1_out2_n                 (<connected-to-hps_0_uart1_out2_n>),                 //                            .out2_n
		.hps_0_uart1_rxd                    (<connected-to-hps_0_uart1_rxd>),                    //                            .rxd
		.hps_0_uart1_txd                    (<connected-to-hps_0_uart1_txd>),                    //                            .txd
		.hps_0_i2c1_out_data                (<connected-to-hps_0_i2c1_out_data>),                //                  hps_0_i2c1.out_data
		.hps_0_i2c1_sda                     (<connected-to-hps_0_i2c1_sda>),                     //                            .sda
		.hps_0_i2c1_clk_clk                 (<connected-to-hps_0_i2c1_clk_clk>),                 //              hps_0_i2c1_clk.clk
		.hps_0_i2c3_scl_in_clk              (<connected-to-hps_0_i2c3_scl_in_clk>),              //           hps_0_i2c3_scl_in.clk
		.hps_0_i2c3_clk_clk                 (<connected-to-hps_0_i2c3_clk_clk>),                 //              hps_0_i2c3_clk.clk
		.hps_0_can0_rxd                     (<connected-to-hps_0_can0_rxd>),                     //                  hps_0_can0.rxd
		.hps_0_can0_txd                     (<connected-to-hps_0_can0_txd>),                     //                            .txd
		.hps_0_i2c3_out_data                (<connected-to-hps_0_i2c3_out_data>),                //                  hps_0_i2c3.out_data
		.hps_0_i2c3_sda                     (<connected-to-hps_0_i2c3_sda>),                     //                            .sda
		.led_pio_external_connection_export (<connected-to-led_pio_external_connection_export>), // led_pio_external_connection.export
		.pb_pio_external_connection_export  (<connected-to-pb_pio_external_connection_export>),  //  pb_pio_external_connection.export
		.sw_pio_external_connection_export  (<connected-to-sw_pio_external_connection_export>),  //  sw_pio_external_connection.export
		.hps_0_h2f_gp_gp_in                 (<connected-to-hps_0_h2f_gp_gp_in>),                 //                hps_0_h2f_gp.gp_in
		.hps_0_h2f_gp_gp_out                (<connected-to-hps_0_h2f_gp_gp_out>)                 //                            .gp_out
	);

