# TCL File Generated by Component Editor 18.1
# Mon Dec 16 13:38:00 CET 2019
# DO NOT MODIFY


# 
# HAN_FanControll "HAN_FanControll" v1.0
# Robin Sebastian 2019.12.16.13:38:00
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module HAN_FanControll
# 
set_module_property DESCRIPTION ""
set_module_property NAME HAN_FanControll
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Basic Functions/I/O"
set_module_property AUTHOR "Robin Sebastian"
set_module_property DISPLAY_NAME HAN_FanControll
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL HAN_FanTempControll
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file HAN_FanTempControll.sv SYSTEM_VERILOG PATH A10_IP/HAN_FanControll/HAN_FanTempControll.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock50Mhz
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point clock50Mhz
# 
add_interface clock50Mhz clock end
set_interface_property clock50Mhz clockRate 0
set_interface_property clock50Mhz ENABLED true
set_interface_property clock50Mhz EXPORT_OF ""
set_interface_property clock50Mhz PORT_NAME_MAP ""
set_interface_property clock50Mhz CMSIS_SVD_VARIABLES ""
set_interface_property clock50Mhz SVD_ADDRESS_GROUP ""

add_interface_port clock50Mhz clk_50Mhz clk Input 1


# 
# connection point IO_I2C_SDA
# 
add_interface IO_I2C_SDA conduit end
set_interface_property IO_I2C_SDA associatedClock clock50Mhz
set_interface_property IO_I2C_SDA associatedReset ""
set_interface_property IO_I2C_SDA ENABLED true
set_interface_property IO_I2C_SDA EXPORT_OF ""
set_interface_property IO_I2C_SDA PORT_NAME_MAP ""
set_interface_property IO_I2C_SDA CMSIS_SVD_VARIABLES ""
set_interface_property IO_I2C_SDA SVD_ADDRESS_GROUP ""

add_interface_port IO_I2C_SDA I2C_SDA_TempFan export Bidir 1


# 
# connection point IO_I2C_SCL
# 
add_interface IO_I2C_SCL conduit end
set_interface_property IO_I2C_SCL associatedClock clock50Mhz
set_interface_property IO_I2C_SCL associatedReset ""
set_interface_property IO_I2C_SCL ENABLED true
set_interface_property IO_I2C_SCL EXPORT_OF ""
set_interface_property IO_I2C_SCL PORT_NAME_MAP ""
set_interface_property IO_I2C_SCL CMSIS_SVD_VARIABLES ""
set_interface_property IO_I2C_SCL SVD_ADDRESS_GROUP ""

add_interface_port IO_I2C_SCL I2C_SCL_TempFan writeresponsevalid_n Output 1


# 
# connection point FAN_ALERT
# 
add_interface FAN_ALERT conduit end
set_interface_property FAN_ALERT associatedClock clock50Mhz
set_interface_property FAN_ALERT associatedReset ""
set_interface_property FAN_ALERT ENABLED true
set_interface_property FAN_ALERT EXPORT_OF ""
set_interface_property FAN_ALERT PORT_NAME_MAP ""
set_interface_property FAN_ALERT CMSIS_SVD_VARIABLES ""
set_interface_property FAN_ALERT SVD_ADDRESS_GROUP ""

add_interface_port FAN_ALERT FAN_ALERT_n beginbursttransfer Input 1


# 
# connection point STATUS_LED
# 
add_interface STATUS_LED conduit end
set_interface_property STATUS_LED associatedClock clock50Mhz
set_interface_property STATUS_LED associatedReset ""
set_interface_property STATUS_LED ENABLED true
set_interface_property STATUS_LED EXPORT_OF ""
set_interface_property STATUS_LED PORT_NAME_MAP ""
set_interface_property STATUS_LED CMSIS_SVD_VARIABLES ""
set_interface_property STATUS_LED SVD_ADDRESS_GROUP ""

add_interface_port STATUS_LED Temp_LED writeresponsevalid_n Output 1


# 
# connection point Temp_Ok
# 
add_interface Temp_Ok conduit end
set_interface_property Temp_Ok associatedClock clock50Mhz
set_interface_property Temp_Ok associatedReset ""
set_interface_property Temp_Ok ENABLED true
set_interface_property Temp_Ok EXPORT_OF ""
set_interface_property Temp_Ok PORT_NAME_MAP ""
set_interface_property Temp_Ok CMSIS_SVD_VARIABLES ""
set_interface_property Temp_Ok SVD_ADDRESS_GROUP ""

add_interface_port Temp_Ok Temp_OK writeresponsevalid_n Output 1


# 
# connection point Temp_low
# 
add_interface Temp_low conduit end
set_interface_property Temp_low associatedClock clock50Mhz
set_interface_property Temp_low associatedReset ""
set_interface_property Temp_low ENABLED true
set_interface_property Temp_low EXPORT_OF ""
set_interface_property Temp_low PORT_NAME_MAP ""
set_interface_property Temp_low CMSIS_SVD_VARIABLES ""
set_interface_property Temp_low SVD_ADDRESS_GROUP ""

add_interface_port Temp_low Temp_LOW writeresponsevalid_n Output 1


# 
# connection point Temp_hi
# 
add_interface Temp_hi conduit end
set_interface_property Temp_hi associatedClock clock50Mhz
set_interface_property Temp_hi associatedReset ""
set_interface_property Temp_hi ENABLED true
set_interface_property Temp_hi EXPORT_OF ""
set_interface_property Temp_hi PORT_NAME_MAP ""
set_interface_property Temp_hi CMSIS_SVD_VARIABLES ""
set_interface_property Temp_hi SVD_ADDRESS_GROUP ""

add_interface_port Temp_hi Temp_HI writeresponsevalid_n Output 1


# 
# connection point avalon_slave_0_1
# 
add_interface avalon_slave_0_1 avalon end
set_interface_property avalon_slave_0_1 addressUnits WORDS
set_interface_property avalon_slave_0_1 associatedClock clock50Mhz
set_interface_property avalon_slave_0_1 associatedReset reset
set_interface_property avalon_slave_0_1 bitsPerSymbol 8
set_interface_property avalon_slave_0_1 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0_1 burstcountUnits WORDS
set_interface_property avalon_slave_0_1 explicitAddressSpan 0
set_interface_property avalon_slave_0_1 holdTime 0
set_interface_property avalon_slave_0_1 linewrapBursts false
set_interface_property avalon_slave_0_1 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0_1 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0_1 readLatency 0
set_interface_property avalon_slave_0_1 readWaitTime 1
set_interface_property avalon_slave_0_1 setupTime 0
set_interface_property avalon_slave_0_1 timingUnits Cycles
set_interface_property avalon_slave_0_1 writeWaitTime 0
set_interface_property avalon_slave_0_1 ENABLED true
set_interface_property avalon_slave_0_1 EXPORT_OF ""
set_interface_property avalon_slave_0_1 PORT_NAME_MAP ""
set_interface_property avalon_slave_0_1 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0_1 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0_1 read read Input 1
add_interface_port avalon_slave_0_1 address address Input 1
add_interface_port avalon_slave_0_1 readdata readdata Output 32
set_interface_assignment avalon_slave_0_1 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0_1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0_1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0_1 embeddedsw.configuration.isPrintableDevice 0

